### ISSUE TITLE
`bun run regtest` errors

### ISSUE THREAD

**Issue by raphjaph** [cypherpunklab/opm#21]
Trying to follow the README but getting:
```
Error: Not enough file descriptors available.
error: script "regtest" exited with code 1 (SIGHUP)
```
when running
```
bun run regtest
```

If I do `sh ./utils/regtest.sh` it works fine. Not familiar with bun so no idea if I'm using it wrong.

**Comment by raphjaph** [comment]
I deleted the whole regtest folder, just to make sure

**Comment by elocremarc** [comment]
Hey thanks for finding these. We just updated to bun and I already had regtest running and forgot to check the create and run commands. Looks like bun doesn't like running shell scripts. I will research if thats possible and maybe just make a TS wrapper to do it.

**Comment by elocremarc** [comment]
@raphjaph do you think Just could be good here for these command running? I haven't really looked into Just yet.

**Comment by raphjaph** [comment]
yeah `just` would be perfect for this!

**Comment by elocremarc** [comment]
Yeah only issue is it would add another dependency. I got the issues resolved for now by making those run as shell scripts. Could maybe use just as a addition. Give it another spin see if you can break something else haha.
