### ISSUE TITLE
`bun run create` doesn't mine blocks

### ISSUE THREAD

**Issue by raphjaph** [cypherpunklab/opm#22]
I ran `bun run create` and then `bun run opm` but get the error that wallet doesn't contain cardinal utxos. `ord -r wallet balance` confirms this. In `utils/create.ts` it shows that it is generating but somehow this doesn't work for me.

**Comment by elocremarc** [comment]
Looks like the init stuff is scuffed rn and `bun run mine` is broken too it seems see screen cap
<img width="369" alt="image" src="https://github.com/cypherpunklab/opm/assets/42568538/c37e661d-eee3-47af-b1f8-b2639baa602b">
However if you get regtest inited normally the rest seems to work as a temporary fix.

**Comment by elocremarc** [comment]
Just moved everything to shell scirpts at the top level see new `README.md`
https://github.com/cypherpunklab/opm/pull/23
